config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :courses do
    resources :appointments, only: [ :new, :create ]
  end

  resources :appointments, only: :destroy
  resources :users, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :student, class_name: "User"
  belongs_to :course
  has_one :teacher, through: :course

  validates :start_time, :end_time, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :teacher, class_name: "User"
  has_one_attached :cover_photo
  has_many :appointments, dependent: :destroy
  validates :title, :description, :category, :price_per_hour, presence: true
  include PgSearch::Model

   pg_search_scope :search_by_title_and_description_and_category,
    against: [ :title, :description, :category ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :owned_courses, foreign_key: :teacher_id, class_name: "Course", dependent: :destroy
  has_many :appointments, dependent: :destroy, foreign_key: :student_id
  has_many :courses, through: :appointments

  validates :last_name, presence: true
  validates :first_name, presence: true
  has_one_attached :profile_photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Pundit white-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  add_flash_types :error, :success, :info

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :profile_photo)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
  end

  # private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^users$)|(^appointments$)/
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @course = Course.find(params[:course_id])
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(course_params)
    @course = Course.find(params[:course_id])
    @user = current_user
    @appointment.course = @course
    @appointment.student = @user
    if @appointment.save
      flash[:success] = "Congratulations! Your appointment is confirmed!🎉"
      redirect_to @course
    else
      flash[:alert] = "We're sorry, this appointment could not be booked. Please try again 😢"
      redirect_to @course
    end
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @user = current_user
    if @appointment.destroy
      flash[:alert] = "You have cancelled this appointment ❌"
      redirect_to @user
    end
  end
  
  private

  def course_params
    params.require(:appointment).permit(:start_time, :end_time)
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  def index
    if params[:query].present?
      @courses = Course.search_by_title_and_description_and_category(params[:query])
    else
      @courses = Course.all.reverse
    end
  end

  def show
    @appointment = Appointment.new
    authorize @course
  end

  def new
    @course = Course.new
    @category = ['Spanish', 'German', 'Chinese', 'Japanese', 'English', 'Math', 'Science', 'Art', 'Music', 'History']
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    @user = current_user
    @course.teacher = @user
    authorize @course
    if @course.save
      redirect_to course_path(@course)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @course.update(course_params)
    redirect_to course_path(@course)
  end

  def destroy
    @course.destroy
    redirect_to courses_path 
  end

  private

  def course_params
    params.require(:course).permit(:title, :category, :description, :price_per_hour, :cover_photo)
  end

  def set_course
    @course = Course.find(params[:id])
    authorize @course
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @courses = Course.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @empty = @user.owned_courses.all? do |course|
      course.appointments.empty?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/new.html.erb
<div class="container">
  <h1>Book this course</h1>
  <%= simple_form_for [ @course, @appointment ] do |f| %>
  <%= f.input :start_time %>
  <%= f.input :end_time%>
  <%= f.button :submit, class: "btn btn-outline-success" %>
  <% end %>
</div>

app/views/courses/edit.html.erb
<div class="container font-custom">
<h2 style="background: none" class="pb-3 ml-0 font-custom">Update your course</h2>
  <%= simple_form_for @course do |f|%>
  <%= f.input :title %>
  <%= f.input :category, collection: @category %>
  <%= f.input :description, as: :text %>
  <%= f.input :price_per_hour %>
  <%= f.button :submit, class: "btn btn-custom" %>
  <% end %>
</div>

app/views/courses/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>Available Courses</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <% if @query %>
      <p>You searched for <strong><%= @query %></strong>. We found <%= @courses.count %> courses out of our
        <%= course.count %> on our website.</p>
      <% else %>
      <p>There are <%= @courses.count %> courses available</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @courses.each do |course| %>
    <div class="col-6 col-md-4 d-flex align-items-stretch">
      <div class="course-card mb-4" style="background-image: min-height: 100%; min-width:
            100%; background-position: center; background-size: cover; box-shadow: 0px 0px 4px #ccc;">
        <% if course.cover_photo.attached? %>
        <%= cl_image_tag course.cover_photo.key, class: "card-img-top" %>
        <% else %>
        <img class="card-img-top"
          src="https://images.unsplash.com/photo-1477281765962-ef34e8bb0967?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1532&q=80"
          alt="">
        <% end %>
        <div class="course-card-image" style=""></div>
        <div class="course-card-content pb-3 px-3">
          <div class="course-card-title">
            <h4 style="margin-top: 8px"><%= course.title %></h4>
            <p class="lead py-2">Category: <%= course.category %></p>
            <p class="p-card"><%= course.description %></p>
            <%= link_to "", course_path(course), class: "stretched-link" %>
          </div>


          <div class="row pt-3 d-sm-flex flex-lg-row">

            <div class="col-12 col-lg-4">
              $<%= course.price_per_hour %>
            </div>
            <div
              class="col-12 col-lg-8 d-flex flex-sm-column flex-md-row pt-sm-2 pt-lg-0 justify-content-between justify-content-lg-end btn-index-card">
              <% if policy(course).edit? %>
              <%= link_to 'Edit', edit_course_path(course), class: 'mr-lg-1 btn btn-custom' %>
              <% end %>
              <% if policy(course).destroy? %>
              <%= link_to "Remove", course_path(course),
                        method: :delete,
                        data: { confirm: "Are you sure you want to delete this course?" },
                        class: 'btn btn-custom'
                      %>
              <% end %>
            </div>
            <!-- <% if course.teacher.profile_photo.attached? %>
                    <%= cl_image_tag course.teacher.profile_photo.key, class: "card-course-user avatar-bordered" %>
                  <% else %>
                    <%= image_tag "user-profile-default.png", class: "card-course-user avatar-bordered" %>
                  <% end %> -->

          </div>

        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<!-- edited -->

app/views/courses/new.html.erb
<div class="container">
  <h1>Create a course</h1>
  <%= simple_form_for @course do |f| %>
  <%= f.input :title %>
  <%= f.input :category, collection: @category %>
  <%= f.input :description, as: :text %>
  <%= f.input :price_per_hour, input_html: { min: '0', step: '1' } %>
  <%= f.input :cover_photo, as: :file  %>
  <%= f.button :submit, class: "btn btn-custom color-white" %>
  <% end %>
</div>

app/views/courses/show.html.erb
<div>
  <% if @course.cover_photo.attached? %>
    <%= cl_image_tag @course.cover_photo.key, class: "cover-photo" %>
  <% else %>
    <%= image_tag "classroom.jpg", class: "cover-photo" %>
  <% end %>
</div>
<div class="container mt-4">
  <div class="row">
    <div class="col-8 d-flex flex-column align-items-center">
      <div class="course-show-card">
        <div class="course-intro">
          <h1>Welcome to <%= @course.title %>!</h1>
          <p class="course-show-address">Course Category: <%= @course.category %></p>
        </div>
        <div class="course-content">
          <div class="row">
            <div class="col-7 course-details">
              <h3 class="mt-3">A bit more about this course...</h3>
              <p><%= @course.description %></p>
            </div>
            <div class="col-4 offset-1 course-details">
              <h5 class="mt-3">Course taught by:</h5>
              <ul class="list-inline">
                <li class="list-inline-item">
                  <% if @course.teacher.profile_photo.attached? %>
                    <%= cl_image_tag @course.teacher.profile_photo.key, class: "avatar-bordered" %>
                  <% else %>
                    <%= image_tag "user-profile-default.png", class: "avatar-bordered" %>
                  <% end %>
                </li>
              <li class="list-inline-item"><%= @course.teacher.first_name %> <%= @course.teacher.last_name %></li>
              </ul>
              <h5 class="mt-4">Price per hour: $<%= @course.price_per_hour %></h5>
            </div>
          </div>
        </div>
        <div>
          <%= link_to "Back to all courses", courses_path, class: "btn btn-custom color-white mt-4 mr-2
          " %>
          <% if policy(@course).edit? %>
                <%= link_to 'Edit', edit_course_path(@course), class: 'mt-4 mr-2 btn btn-custom' %>
                <% end %>
          <% if policy(@course).destroy? %>
          <%= link_to "Remove", course_path(@course),
                    method: :delete,
                    data: { confirm: "Are you sure you want to delete this course?" },
                    class: "btn btn-custom color-white mt-4 "
                  %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Book this course!</h5>
          <%= simple_form_for [ @course, @appointment ] do |f| %>
          <%= f.input :start_time, as: :date, html5: true %>
          <%= f.input :end_time, as: :date, html5: true %>
          <% if current_user != @course.teacher %>
          <%= f.submit "Book", class: "btn btn-custom color-white btn-block" %>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Schoolgoal</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>


<body>
  <div class="site-container">
    <main class="site-content">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </main>
    <footer class="site-footer">
      <%= render 'shared/footer' %>
    </footer>
  </div>
</body>

</html>

app/views/pages/home.html.erb
<!-- <div
  class="jumbotron jumbotron-fluid m-0 bg-transparent text-center d-flex flex-column justify-content-center align-items-center">
  <h1 class="display-4 custom-font">schoolgoal</h1>
  <%= link_to "Our courses", courses_path, class: "btn btn-custom" %>
</div> -->
<div class="jumbotron jumbotron-fluid">
  <div class="container j-container d-flex flex-column align-items-center">
    <h1 id="feature-header" class="display-4 custom-font">schoolgoal</h1>
    <%= link_to "Our courses", courses_path, class: "btn btn-custom" %>
  </div>
</div>
<br>
</div>
<div class="pt-6 pb-7">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto text-center">
        <h3 class="bold pb-2 color-custom">Why Schoolgoal?</h3>
        <p class="text-muted lead">You can now access the best teachers from around the world from your cell phone or
          computer</p>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-md-10 mx-auto">
        <div class="row feature-boxes">
          <div class="col-md-6 box">
            <div class="icon-box box-primary">
              <div class="icon-box-inner">
                <span data-feather="edit-3" width="35" height="35"></span>
              </div>
            </div>
            <h5><strong>Freedom of Choice</strong></h5>
            <p class="text-muted lead">Choose your own teachers based on their credentials, location, and teaching
              style</p>
          </div>
          <div class="col-md-6 box">
            <div class="icon-box box-success">
              <div class="icon-box-inner">
                <span data-feather="monitor" width="35" height="35"></span>
              </div>
            </div>
            <h5><strong>Personalize your experience</strong></h5>
            <p class="text-muted lead">Communicate your teaching style and needs with comprehensive and culturally
              responsive feedback</p>
          </div>
          <div class="col-md-6 box">
            <div class="icon-box box-danger">
              <div class="icon-box-inner">
                <span data-feather="layout" width="35" height="35"></span>
              </div>
            </div>
            <h5><strong>Design your own courses</strong></h5>
            <p class="text-muted lead">As a teacher you can teach required courses or design your own curriculum</p>
          </div>
          <div class="col-md-6 box">
            <div class="icon-box box-info">
              <div class="icon-box-inner">
                <span data-feather="globe" width="35" height="35"></span>
              </div>
            </div>
            <h5><strong>Be your own boss</strong></h5>
            <p class="text-muted lead">Create your own schedule and utilize your own pedagogical style with feedback
              from
              students</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row mt-6">
      <div class="col-md-6 mr-auto">
      </div>
    </div>
  </div>
</div>
<hr>
<div class="container pt-2">

  <h2 class="text-center font-custom pb-4">Explore Featured Courses</h2>

  <div class="row row-cols-1 row-cols-md-3">
    <div class="col mb-4">
      <div class="card h-100 featured-card border-0 rounded">
        <% if @courses[0].cover_photo.attached? %>
        <%= cl_image_tag @courses[0].cover_photo.key, class: "card-img-top" %>
        <% else %>
        <img
          src="https://images.unsplash.com/photo-1518152006812-edab29b069ac?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"
          class="card-img-top" alt="...">
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= @courses[0].title %></h5>
          <p class="card-text"><%= @courses[0].description %></p>
        </div>
        <div class="card-footer">
          <%= link_to "Check out more", course_path(@courses[0]), class: "btn btn-custom btn-lg btn-block" %>
        </div>
      </div>
    </div>

    <div class="col mb-4">
      <div class="card h-100 featured-card border-0 rounded">
        <% if @courses[1].cover_photo.attached? %>
        <%= cl_image_tag @courses[1].cover_photo.key, class: "card-img-top" %>
        <% else %>
        <img
          src="https://images.unsplash.com/photo-1499332347742-4946bddc7d94?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=633&q=80"
          class="card-img-top" alt="...">
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= @courses[1].title %></h5>
          <p class="card-text"><%= @courses[1].description %></p>
        </div>
        <div class="card-footer">
          <%= link_to "Check out more", course_path(@courses[1]), class: "btn btn-custom btn-lg btn-block" %>
        </div>
      </div>
    </div>
    <div class="col mb-4">
      <div class="card h-100 featured-card border-0 rounded">
        <% if @courses[2].cover_photo.attached? %>
        <%= cl_image_tag @courses[2].cover_photo.key, class: "card-img-top" %>
        <% else %>
        <img
          src="https://images.unsplash.com/photo-1553695142-4bb5259028e2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80"
          class="card-img-top" alt="...">
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= @courses[2].title %></h5>
          <p class="card-text"><%= @courses[2].description %></p>
        </div>
        <div class="card-footer">
          <%= link_to "Check out more", course_path(@courses[2]), class: "btn btn-custom btn-lg btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if success %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= success %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer p-3 mt-5 custom-footer bg-white">
  <div class="container">
    <div class="row">
      <div class="col-12 pt-2 text-muted text-center small-xl">
        &#169;schoolgoal 2020
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm bg-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand color-custom pb-0 mb-0 ml-3" do %>
    <%= image_tag "wave.png" %>
    <p class="d-inline">
      schoolgoal
    </p>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= form_tag courses_path, method: :get, class: "form-inline my-2 my-lg-0" do %>
    <%= text_field_tag :query,
          params[:query],
          class: "form-control search-form mr-sm-2",
          placeholder: "Search for a course"
        %>
    <!-- <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %> -->
    <% end %>
    <ul class="navbar-nav mr-auto pr-4">
      <% if user_signed_in? %>
      <li class="nav-item">
        <% if policy(Course).create? %>
        <%= link_to "Create a Course", "/courses/new", class: "nav-link color-custom" %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to "Find a Course", courses_path, class: "nav-link color-custom" %>
      </li>
      <li class="nav-item dropdown">
        <% if current_user.profile_photo.attached? %>
        <%= cl_image_tag current_user.profile_photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
        <%= image_tag "user-profile-default.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right rounded" aria-labelledby="navbarDropdown">
          <h6 class="border-bottom pl-3 py-1">Hi <strong><%= current_user.first_name %></strong>! 😄</h6>
          <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link color-custom" %>
      </li>
      <% end %>
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <h3 class="text-center profile-header">My Profile</h3>
      <div class="profile">
        <% if @user.profile_photo.attached?  %>
          <%= cl_image_tag @user.profile_photo.key, class: "profile-pic" %>
        <% else %>
          <%= image_tag "user-profile-default.png", class: "profile-pic" %>
        <% end %>
        <h3 class="profile-header"><%= @user.first_name %> <%= @user.last_name %></h3>
        <h6><i class="fas fa-envelope-square"></i> <%= @user.email %></h6>
      </div>
    </div>
    <div class="col-9 upcoming-appointments">
      <div class="row">
        <div class="col-12">
          <% if not @user.owned_courses.empty? %>
            <h3 class="profile-header">My Published Courses</h3>
            <div class="cards">
              <% @user.owned_courses.each do |owned_course| %>
                <%= link_to course_path(owned_course), class: "link-to-course" do %>
                  <% if owned_course.cover_photo.attached? %>
                    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path owned_course.cover_photo.key %>')">
                      <%= owned_course.title %>
                      <p class="course-category"><%= owned_course.category %></p>
                    </div>
                  <% else %>
                    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1509062522246-3755977927d7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1104&q=80)">
                      <%= owned_course.title %>
                      <p class="course-category"><%= owned_course.category %></p>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          <% else %>
            <h4 class="my-5">You don't have any published courses, <%= link_to "create one now!", new_course_path %></h4 class="my-5">
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <% if not @user.owned_courses.empty? %>
            <% if not @empty %>
              <h3 class="profile-header">My Upcoming Teaching Sessions</h3>
              <% @user.owned_courses.each do |owned_course| %>
                <% if not owned_course.appointments.empty? %>
                  <div class="card-product">
                    <% if owned_course.cover_photo.attached? %>
                      <%= cl_image_tag owned_course.cover_photo.key %>
                    <% else %>
                      <img src="https://images.unsplash.com/photo-1509062522246-3755977927d7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1104&q=80" alt="course">
                    <% end %>
                    <div class="card-product-infos">
                      <h3><%= owned_course.title %></h3>
                      <h6><%= owned_course.category %></h4>
                      <% owned_course.appointments.order(start_time: :asc).each do |tsession| %>
                        <p>
                          <strong>Student:</strong> <%= tsession.student.first_name %> <%= tsession.student.last_name %>. 
                          <strong>On:</strong> <%= tsession.start_time %>
                        </p>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% else %>
              <h3 class="profile-header">You don't have any upcoming teaching sessions</h3>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <% if not @user.appointments.empty? %>
            <h3 class="profile-header">My Upcoming Study Sessions</h3>
            <% @user.appointments.order(start_time: :asc).each do |appointment| %>
              <ul class="list-group list-group-flush">
                <li class="list-group-item appointment-list">
                  <%= appointment.course.title %> - <%= appointment.course.category %> <%= link_to "❌", appointment_path(appointment),
                    method: :delete,
                    data: { confirm: "Are you sure you want to delete this appointment?" }
                  %>
                  <br>
                  <strong>Teacher:</strong> <%= appointment.course.teacher.first_name %> <%= appointment.course.teacher.last_name %>
                  <br>
                  <strong>On:</strong> <%= appointment.start_time %>
                </li>
              </ul>
            <% end %>
          <% else %>
            <h4 class="my-5">You don't have any upcoming learning sessions, <%= link_to "browse our courses now!", courses_path %></h4 class="mb-5">
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>